services:
  mongo:
    image: mongo:latest
    container_name: sepetix-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always


volumes:
  mongo_data:  